### ISSUE TITLE
Replace Static IP -> Wifimanager

### ISSUE THREAD

**Issue by Starsurfer78** [Boilevin/AzuritBer#1]
It would be nice if you replace the static IP management in Sender ESP with the Arduino Wifimanager.
[Wifimanager Examples](https://diyprojects.io/esp32-test-wifimanager-library-manage-wifi-connections/)
I thinks it's more flexible, as a static IP Adress

**Comment by Boilevin** [comment]
I see this github part for the first time.

Many ESP32 library are always in dev mode and don't work correctly.
My test show many bug on auto reconnect  ( append only one time each day or week and connection is lost )
It's why you can see a full reset of the sender in particular response code (err 2 if i remenber well).
The actual code work for more than month without any trouble with static IP 

It's also possible to use the mower as access point,so it's easier to use static IP to have same value from your routeur and the raspberry.

If you have DHCP working code, you can send it in Ardumower PM or Forum
