### ISSUE TITLE
Add support for backup/restore EEPROM data

### ISSUE THREAD

**Issue by Latek** [Boilevin/AzuritBer#2]
Did:
Tried to backup my settings from EEPROM.

Happened:
There's no such option.

Expected:
To have a similar option to backup/restore like in the standard Azurit software.

**Comment by Latek** [comment]
I've tried to move the code responsible for dump/restore EPROM data from Azurit project but failed to get it working. 

This is what I've done:
1. Replaced current flashmem.cpp and flashmem.h content to the one I've found in Azurit project.
2. Added Console menu options to backup/restore settings.
3. I was able to backup.
4. I was not able to restore. While restoring the system is always restarting and does not finish flashing data to EEPROM.

**Comment by Boilevin** [comment]
I take a look.
But if you have raspberry ,it's easier to save and restore using PiArdu.

**Comment by Boilevin** [comment]
Ok.

4. I was not able to restore. While restoring the system is always restarting and does not finish flashing data to EEPROM

AZURITBER use a DUE native hardware watchdog set at 2 secondes, so you need to reset it after each delay(500) or never use something like delay(2001) or DUE reset occur
Also write to eeprom take time , so put this watchdogReset(); everywhere code take time to run.

 while (Console.available()) Console.read();              
    delay(500);
    watchdogReset();

  }
