### ISSUE TITLE
raspberry pi restart problem

### ISSUE THREAD

**Issue by szurr** [Boilevin/AzuritBer#3]
hi 
firstly thanks for great work as i wrote this issue i solved it but i think there is a missing part in tutorial ore git files.
I installed all as in tutrial (in fact 3 times) i made permissions and dostounix and still i can't reboot PI. I get this eror:

09:13:21 ERROR PLEASE CHECK TRACEBACK INFO
09:13:21 ['Traceback (most recent call last):\n', '  File "PiArdu.py", line 617, in checkSerial\n    decode_message(message)\n', '  File "PiArdu.py", line 775, in decode_message\n    ButtonSaveReceived_click()  #save the console txt\n', '  File "PiArdu.py", line 1856, in ButtonSaveReceived_click\n    with open(fileName,"w") as f:\n', "FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/Documents/PiArdumower/log/202104290913_Received.txt'\n"]09:13:21 FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/Documents/PiArdumower/log/202104290913_Received.txt'09:13:21 Traceback (most recent call last):09:13:21 None09:13:21 Start to save all Console Data
09:13:21 PI Restart into 5 Seconds

i saw that i don't have folder log in PiArdumower. i added it manually and then it start to reboot correctly.
i submit but feel free to close or delete.

thanks again and have a nice day

**Comment by Boilevin** [comment]
Thanks .
I am going to discover that empty folder are not manage as news in my github desktop !!
I add a file inside and now it's OK.
